title: Pragathi Ravindranath
logo: /assets/img/logo.png
description: 
  <p align="center">
  <br>   
  I'm working as a Data Scientist 
  <br>
  </p>

show_downloads: false
theme: jekyll-theme-minimal
